# Generated by Django 4.2.7 on 2026-08-28 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('PASSWORD_CHANGE', 'Password Change'), ('PROFILE_UPDATE', 'Profile Update'), ('PRODUCT_CREATE', 'Product Created'), ('PRODUCT_UPDATE', 'Product Updated'), ('PRODUCT_DELETE', 'Product Deleted'), ('ORDER_CREATE', 'Order Created'), ('ORDER_CANCEL', 'Order Cancelled'), ('ORDER_STATUS_UPDATE', 'Order Status Updated'), ('PAYMENT_CREATE', 'Payment Created'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('INVENTORY_UPDATE', 'Inventory Updated'), ('REVIEW_CREATE', 'Review Created'), ('REVIEW_DELETE', 'Review Deleted'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deleted'), ('CATEGORY_CREATE', 'Category Created'), ('CATEGORY_UPDATE', 'Category Updated'), ('CATEGORY_DELETE', 'Category Deleted'), ('CART_ADD', 'Cart Add'), ('CART_REMOVE', 'Cart Remove'), ('WISHLIST_ADD', 'Wishlist Add'), ('WISHLIST_REMOVE', 'Wishlist Remove'), ('ML_TRAIN', 'ML Model Trained'), ('ML_PREDICT', 'ML Prediction Run'), ('REPORT_GENERATE', 'Report Generated'), ('ADMIN_ACTION', 'Admin Action'), ('SELLER_ACTION', 'Seller Action'), ('FRAUD_ALERT', 'Fraud Alert'), ('SYSTEM', 'System Event')], db_index=True, max_length=50)),
                ('module', models.CharField(db_index=True, help_text='Application module where the action occurred', max_length=100)),
                ('description', models.TextField()),
                ('object_type', models.CharField(blank=True, help_text='The type of object affected (e.g., Product, Order)', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='The ID of the affected object', max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional context data as JSON')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['module', 'timestamp'], name='audit_audit_module_21e939_idx')],
            },
        ),
    ]
